name: Build

on:
  push:
    branches:
    - main
    - release-*
  pull_request:
    branches:
    - main
    - release-*
    - gh-ci

env:
  # renovate: datasource=go depName=mvdan.cc/gofumpt
  GOFUMPT_VERSION: v0.5.0
  # renovate: datasource=go depName=github.com/golangci/golangci-lint
  GOLANGCI_LINT_VERSION: v1.53.3
  # renovate: datasource=go depName=github.com/florianl/bluebox
  BLUEBOX_VERSION: v0.0.1

jobs:
  skip-check:
    name: Skip check
    continue-on-error: true
    runs-on: ubuntu-latest
    outputs:
      should_skip: ${{ steps.skip-check.outputs.should_skip }}
    permissions:
      actions: write
      contents: read
    steps:
      - id: skip-check
        uses: fkirc/skip-duplicate-actions@12aca0a884f6137d619d6a8a09fcc3406ced5281 # v5.3.0
        with:
          do_not_skip: '["schedule", "workflow_dispatch"]'
          paths: |-
            [
              "**.go",
              ".github/workflows/build.yml",
              ".go-version",
              "3rdparty",
              "Makefile",
              "bpf/**",
              "go.mod",
              "go.sum",
              "kerneltest/**"
            ]
          skip_after_successful_duplicate: false

  vmtest:
    name: kernel tests
    runs-on: ubuntu-latest
    needs: go-build-test
    if: ${{ needs.skip-check.outputs.should_skip != 'true' }}
    steps:
      - name: Check out the code
        uses: actions/checkout@c85c95e3d7251135ab7dc9ce3241c5835cc595a9 # v3.5.3

      - name: Install dependencies
        run: |
          sudo apt-get update -y
          sudo apt -y install qemu-system-x86 curl

      - name: Download previously generated initramfs
        uses: actions/download-artifact@9bc31d5ccc31df68ecc42ccf4149144866c47d8a # v3.0.2
        with:
          name: initramfs
          path: kerneltest/

      - name: Run vmtests
        run: ./kerneltest/vmtest.sh
